# File: docker-compose.yml
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# Call example:
# $ docker-compose up

version: "3"

services:

  db:
    image: mysql
    env_file: 
      - .env
    container_name: ${COMPOSE_PROJECT_NAME}_db
    environment:
      - MYSQL_DATABASE=ojs_${COMPOSE_PROJECT_NAME}
    volumes:
      - /srv/mysql/journal:/var/lib/mysql # I want data to be stored outside docker.
#      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.

  ojs:
    image: marcbria/docker4ojs:version
    env_file: 
      - .env
    container_name: ${COMPOSE_PROJECT_NAME}_ojs
    hostname: ${COMPOSE_PROJECT_NAME}
    healthcheck:
      test: "exit 0"
    environment:
      - OJS_BRANCH=${OJS_BRANCH}
    ports:
      - "${OJS_PORT}:80"
    links:
      - db:db
    extra_hosts:
      - "${COMPOSE_PROJECT_NAME}.${PROJECT_DOMAIN}:127.0.0.1"
    depends_on:
      - db
