# File: docker-compose.yml
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# OJS setup:
# - Database type: MySQLi
# - Host: db
# - Database name: ojs
# - Database username: ojs
# - Database password: ojs
#
# Call example:
# $ docker-compose up
#
# ToDo: add extra_hosts

version: "3"

services:

  mariadb:
    image: mariadb:${MYSQL_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
#    volumes:
#      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
#      - /path/to/mariadb/data/on/host:/var/lib/mysql # I want to manage volumes manually.

  ojs:
    image: marcbria/docker4ojs:experimental
    ports:
      - "80"
    links:
      - mariadb:db
    extra_hosts:
      - "${OJS_TAG}.${OJS_DOMAIN}:127.0.0.1"
