# File: docker-compose.yml
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# OJS setup:
# - Database type: MySQLi
# - Host: db
# - Database name: ojs
# - Database username: ojs
# - Database password: ojs
#
# Call example:
# $ docker-compose up

ojs:
  image: marcbria/docker4ojs:latest
  environment:
    - OJS_BRANCH=master
  ports:
    - 8080:80
  links:
    - mysql:db
mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=ojs
    - MYSQL_USER=ojs
    - MYSQL_PASSWORD=ojs
