# File: docker-compose.yml
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# OJS setup:
# - Database type: MySQLi
# - Host: db
# - Database name: ojs
# - Database username: ojs
# - Database password: ojs
#
# Call example:
# $ docker-compose up
#
# ToDo: add extra_hosts

version: "3"

services:

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ojs
      - MYSQL_USER=ojs
      - MYSQL_PASSWORD=ojs

  ojs:
    image: marcbria/docker4ojs:version
    environment:
      - OJS_BRANCH=ojs-stable-3_0_2
    ports:
      - "80"
    links:
      - mysql:db
    extra_hosts:
      - "myOJS.com:127.0.0.1"
