# File: docker-compose.yml
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# Call example:
# $ docker-compose up

version: "3"

services:

  db:
    image: mysql
    env_file: 
      - .env
    container_name: ${COMPOSE_PROJECT_NAME}_db
    environment:
      - MYSQL_DATABASE=ojs_${COMPOSE_PROJECT_NAME}
    volumes:
      - ./db:/var/lib/mysql                       # Stored db data outside docker is recommended.
      # - ./db/init:/docker-entrypoint-initdb.d        # Place init .sql file(s) here.

  adminer:
    image: adminer
    ports:
      - 9001:8080
    links:
      - db:db
    depends_on:
      - db

  ojs:
    image: marcbria/docker4ojs:experimental
    env_file: 
      - .env
    container_name: ${COMPOSE_PROJECT_NAME}_ojs
    hostname: ${COMPOSE_PROJECT_NAME}
    healthcheck:
      test: "exit 0"
    environment:
      - OJS_BRANCH=${OJS_BRANCH}
    ports:
      - "${OJS_PORT}:80"
    links:
      - db:db
    volumes:
      - ./files/private:/var/www/files                 # Stored files outside docker is recommended.
      - ./plugins:/var/www/html/plugins                # Store plugins outside docker to let you modify or add new ones.
      - ./config/apache.htaccess:/var/www/html/.htaccess
      - ./config/ojs.config.inc.php:/var/www/html/config.inc.php
      - ./config/php.custom.ini:/usr/local/etc/php/conf.d/custom.ini
    extra_hosts:
      - "${COMPOSE_PROJECT_NAME}.${PROJECT_DOMAIN}:127.0.0.1"
      - "revistes.uab.test:158.109.174.224"
    depends_on:
      - db
