version: '3.3'

networks:
  traefik:
    external:
      name: traefik
  inside:
    external: false

services:
  traefik:
    image: traefik
    networks:
      - inside
      - traefik 
    ports:
      - "81:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/traefik.toml
      - $PWD/acme.json:/acme.json
#      - $PWD/traefik.log:/traefik.log
    labels:
      - traefik.backend=traefik
      - traefik.frontend.rule=Host:precarietat.net
      - traefik.enable=true
    restart: always
