version: '3.3'

networks:
  outside:
    external: true
#    name: outside
  inside:
    external: false
#    name: inside
#    driver: bridge

services:
  traefik:
    image: traefik
#    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    networks:
      - inside
      - outside
    ports:
#      - "80:80"
      - "81:80"
      - "444:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/traefik.toml
      - $PWD/acme.json:/acme.json
#      - $PWD/traefik.log:/traefik.log
    labels:
      - traefik.backend=traefik
      - traefik.frontend.rule=Host:ada.uab.cat
      - traefik.enable=true
    restart: always
