logLevel = "INFO"
# logLevel = "DEBUG"
# defaultEntryPoints = ["http", "https", "9000", "81", "444"]
defaultEntryPoints = ["http", "https"]

################################################################
# Docker configuration backend
################################################################
# Connection to docker host system (docker.sock)
[docker]
  domain = "precarietat.net"
  watch = true

# WEB interface of Traefik - it will show web page with overview
# of frontend and backend configurations
[web]
  address = ":8080"
  [web.auth.basic]
  # Tip: boss.num
  users = ["admin:$apr1$SeDtNTw2$wkqNuM5fuA7pbc3aZQydR/"]
  [web.statistics]
    RecentErrors = 10

[entryPoints]
  [entryPoints.http]
  address = ":80"
