# File: docker-compose.yml
# Access via "http://localhost:8081"
#   (or "http://$(docker-machine ip):8081" if using docker-machine)
#
# Call example:
# $ docker-compose up

version: "3.3"

networks:
  inside:
    external: false

services:

  db:
    image: mariadb:10.2
    env_file: 
      - .env
    container_name: ${COMPOSE_PROJECT_NAME}_db
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./db:/var/lib/mysql                                          # Stored db data outside docker is recommended.
      # - ./db/init:/docker-entrypoint-initdb.d                      # Place init .sql file(s) here.
    networks:
      - inside
    restart: always

  ojs:
    image: marcbria/docker-pkp-ojs:3.1.1-2
    env_file: 
      - .env
    environment:
      SERVERNAME: ${COMPOSE_PROJECT_NAME}.${PROJECT_DOMAIN}
      OJS_CLI_INSTALL: 1
      OJS_DB_HOST: 'db'
    container_name: ${COMPOSE_PROJECT_NAME}_ojs
    hostname: ${COMPOSE_PROJECT_NAME}
    healthcheck:
      test: "exit 0"
    ports:
      - "${OJS_HTTP}:80"
      - "${OJS_HTTPS}:443"
    volumes:
      - "/etc/localtime:/etc/localtime"
#      - "/volumes/ojs/config.inc.php:/var/www/html/config.inc.php"  # From lucasdietrich (deprecated)
      - ./files/private:/var/www/files
      - ./files/public:/var/www/html/public                          # Stored files outside docker is recommended.
      - ./files/logs:/var/log/apache2                                # Stored files outside docker is recommended.
      - ./config/apache.htaccess:/var/www/html/.htaccess
      - ./config/ojs.config.inc.php:/var/www/html/config.inc.php
      - ./config/php.custom.ini:/etc/php5/conf.d/custom.ini
    labels:
      - "traefik.backend=${COMPOSE_PROJECT_NAME}_ojs"
      - "traefik.port=${OJS_HTTP}"
      - "traefik.frontend.rule=Host:${COMPOSE_PROJECT_NAME}.ada.uab.cat"
      - traefik.enable=true
    networks:
      - inside
    depends_on:
      - db
    restart: always

#  adminer:
#    image: adminer
#    ports:
#      - ${ADMINER_HTTP}:8080
#    links:
#      - db:db
#    networks:
#      - inside
#    depends_on:
#      - db
